//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_arm_h_H
#define METASPRITE_arm_h_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define arm_h_TILE_ORIGIN 0
#define arm_h_TILE_W 8
#define arm_h_TILE_H 16
#define arm_h_WIDTH 24
#define arm_h_HEIGHT 16
#define arm_h_TILE_COUNT 6
#define arm_h_PALETTE_COUNT 1
#define arm_h_COLORS_PER_PALETTE 4
#define arm_h_TOTAL_COLORS 4
#define arm_h_PIVOT_X 12
#define arm_h_PIVOT_Y 8
#define arm_h_PIVOT_W 24
#define arm_h_PIVOT_H 16

BANKREF_EXTERN(arm_h)

extern const palette_color_t arm_h_palettes[4];
extern const uint8_t arm_h_tiles[96];

extern const metasprite_t* const arm_h_metasprites[1];

#endif
