//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_arm_v_back_H
#define METASPRITE_arm_v_back_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define arm_v_back_TILE_ORIGIN 0
#define arm_v_back_TILE_W 8
#define arm_v_back_TILE_H 16
#define arm_v_back_WIDTH 16
#define arm_v_back_HEIGHT 32
#define arm_v_back_TILE_COUNT 24
#define arm_v_back_PALETTE_COUNT 1
#define arm_v_back_COLORS_PER_PALETTE 4
#define arm_v_back_TOTAL_COLORS 4
#define arm_v_back_PIVOT_X 8
#define arm_v_back_PIVOT_Y 16
#define arm_v_back_PIVOT_W 16
#define arm_v_back_PIVOT_H 32

BANKREF_EXTERN(arm_v_back)

extern const palette_color_t arm_v_back_palettes[4];
extern const uint8_t arm_v_back_tiles[384];

extern const metasprite_t* const arm_v_back_metasprites[3];

#endif
