//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_game_finished_H
#define METASPRITE_game_finished_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define game_finished_TILE_ORIGIN 0
#define game_finished_TILE_W 8
#define game_finished_TILE_H 8
#define game_finished_WIDTH 160
#define game_finished_HEIGHT 144
#define game_finished_TILE_COUNT 91
#define game_finished_PALETTE_COUNT 1
#define game_finished_COLORS_PER_PALETTE 4
#define game_finished_TOTAL_COLORS 4
#define game_finished_MAP_ATTRIBUTES 0

BANKREF_EXTERN(game_finished)

extern const palette_color_t game_finished_palettes[4];
extern const uint8_t game_finished_tiles[1456];

extern const unsigned char game_finished_map[360];

#endif
