//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_gbcompologo_H
#define METASPRITE_gbcompologo_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define gbcompologo_TILE_ORIGIN 0
#define gbcompologo_TILE_W 8
#define gbcompologo_TILE_H 8
#define gbcompologo_WIDTH 160
#define gbcompologo_HEIGHT 144
#define gbcompologo_TILE_COUNT 67
#define gbcompologo_PALETTE_COUNT 1
#define gbcompologo_COLORS_PER_PALETTE 4
#define gbcompologo_TOTAL_COLORS 4
#define gbcompologo_MAP_ATTRIBUTES 0

BANKREF_EXTERN(gbcompologo)

extern const palette_color_t gbcompologo_palettes[4];
extern const uint8_t gbcompologo_tiles[1072];

extern const unsigned char gbcompologo_map[360];

#endif
