//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_player_dead_H
#define METASPRITE_player_dead_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define player_dead_TILE_ORIGIN 0
#define player_dead_TILE_W 8
#define player_dead_TILE_H 16
#define player_dead_WIDTH 24
#define player_dead_HEIGHT 16
#define player_dead_TILE_COUNT 6
#define player_dead_PALETTE_COUNT 1
#define player_dead_COLORS_PER_PALETTE 4
#define player_dead_TOTAL_COLORS 4
#define player_dead_PIVOT_X 12
#define player_dead_PIVOT_Y 8
#define player_dead_PIVOT_W 24
#define player_dead_PIVOT_H 16

BANKREF_EXTERN(player_dead)

extern const palette_color_t player_dead_palettes[4];
extern const uint8_t player_dead_tiles[96];

extern const metasprite_t* const player_dead_metasprites[1];

#endif
