//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_soldier_H
#define METASPRITE_soldier_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define soldier_TILE_ORIGIN 0
#define soldier_TILE_W 8
#define soldier_TILE_H 16
#define soldier_WIDTH 16
#define soldier_HEIGHT 32
#define soldier_TILE_COUNT 8
#define soldier_PALETTE_COUNT 2
#define soldier_COLORS_PER_PALETTE 4
#define soldier_TOTAL_COLORS 8
#define soldier_PIVOT_X 8
#define soldier_PIVOT_Y 16
#define soldier_PIVOT_W 16
#define soldier_PIVOT_H 32

BANKREF_EXTERN(soldier)

extern const palette_color_t soldier_palettes[8];
extern const uint8_t soldier_tiles[128];

extern const metasprite_t* const soldier_metasprites[1];

#endif
